# Generated by Django 5.2.8 on 2025-11-20 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique project name', max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(help_text='Detailed description of the project', verbose_name='Project Description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20, verbose_name='Project Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('members', models.ManyToManyField(blank=True, help_text='Team members working on this project', related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Members')),
                ('owner', models.ForeignKey(help_text='User who created and owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'), models.Index(fields=['status'], name='projects_pr_status_f023cb_idx')],
            },
        ),
    ]
